from setuptools import setup, find_packages

setup(
    name="dreamer-sokoban",
    version="0.1.0",
    description="DreamerV3 implementation for Sokoban puzzle solving",
    author="DreamerSokoban Research Team",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.8",
    install_requires=[
        "torch>=2.0.0",
        "torchvision>=0.15.0",
        "gymnasium>=0.28.1",
        "numpy>=1.21.0",
        "matplotlib>=3.5.0",
        "gym-sokoban",
        "griddly",
        "wandb",
        "tensorboard",
        "hydra-core==1.3.2",
        "omegaconf==2.3.0",
        "seaborn",
        "plotly",
        "pandas",
        "scipy",
        "einops",
        "tensordict",
        "stable-baselines3",
        "tqdm",
        "pillow",
        "opencv-python",
        "imageio",
        "pyyaml",
    ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
)
